### ISSUE TITLE
Typo on Developer Dashboard "Tools" page

### ISSUE THREAD

**Issue by osowski** [cloud-native-toolkit/developer-dashboard#40]
The Tekton card on the Tools tab of the Developer Dashboard is incorrectly spelled as **Tekon**.

I tried to dig through really quick to see where that string was coming from, but I could not find it easily or else I would have submitted a PR for it.

<img width="1440" alt="Screen Shot 2021-02-08 at 12 02 19 PM" src="https://user-images.githubusercontent.com/3410195/107261981-9e691680-6a05-11eb-86c9-67b9261a2fbf.png">

**Comment by mjperrins** [comment]
Good spot, 

```
 {
    "title": "Tekon",
    "subTitle": "Manage your build pipelines",
    "reference" : "tekton",
    "iconBase64" 

```

This is the file

https://raw.githubusercontent.com/ibm-garage-cloud/developer-dashboard/main/server/config/tools.json

**Comment by mjperrins** [comment]
Let me know if you want to do the PR or shall I do it ?
